image: alpine/edge
packages:
  - openjdk8
sources:
  - https://git.sr.ht/~klg71/keycloakmigration
tasks:
  - build: |
      cd keycloakmigration
      chmod +x gradlew
      .\\gradlew build
  - publish: |
      cd keycloakmigration
      chmod +x gradlew
      .\\gradlew artifactoryPublish