image: alpine/edge
packages:
  - openjdk8
sources:
  - https://git.sr.ht/~klg71/keycloakmigration
tasks:
  - build: |
      ls
      chmod +x gradlew
      .\\gradlew build
  - publish: |
      chmod +x gradlew
      .\\gradlew artifactoryPublish